server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG

jwt:
  secret: a6e21884876f43819523c31033fa697e

spring:
  datasource:
    url: jdbc:h2:file:~/seed
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    max-active: 10
    max-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000
    min-idle: 8
    time-between-eviction-runs-millis: 1


  h2:
    console:
      enabled: true
      path: /h2